title: Gyongyosi Gabor
default_lang: en
author:
  name: Gyongyosi Gabor
  email: gyongyosigabor@gshoots.hu
taxonomies:
  - category
  - tag
metadata:
  description: 'IT Systems Integrator & Open Source Developer CV'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
description: 'IT Systems Integrator | Open Source Developer | Hardware Specialist'
website: "links.gshoots.hu"
address:
  - line: 'Budapest'
  - line: 'Hungary'
contact:
  - line: "gyongyosigabor@gshoots.hu"
  - line: "+36 50 105 4964"
  - text: "@megvadulthangya"
    url: "https://github.com/megvadulthangya"
    icon: "brands fa-github"  # Vagy "brands fa-github" ha pontos akarsz lenni
    target: "_blank"
