title: Gyöngyösi Gábor
default_lang: hu
author:
  name: Gyöngyösi Gábor
description: 'Rendszerintegrátor | Open Source Fejlesztő | Hardver Specialista'
metadata:
  description: 'IT Rendszermérnök és Fejlesztő Önéletrajz'
address:
  - line: 'Budapest'
  - line: 'Magyarország'
